"""AI reasoning layer models."""

from __future__ import annotations

from pydantic import BaseModel, Field


class AIConstraint(BaseModel):
    """A single inferred constraint from AI reasoning."""

    table: str = ""
    column: str = ""
    constraint_type: str  # e.g. "range", "format", "dependency", "business_rule", "edge_case"
    description: str
    suggestion: dict = Field(default_factory=dict)


class AIEdgeCase(BaseModel):
    """An edge-case instruction generated by AI."""

    table: str = ""
    column: str = ""
    scenario: str
    test_value: str | int | float | bool | None = None


class AIReasoningResult(BaseModel):
    """Full output from the AI reasoning layer."""

    hidden_constraints: list[AIConstraint] = Field(default_factory=list)
    business_rules: list[AIConstraint] = Field(default_factory=list)
    edge_cases: list[AIEdgeCase] = Field(default_factory=list)
    provider: str = ""  # "gateway" or "offline"
    raw_response: str = ""


class AIProviderConfig(BaseModel):
    """Configuration for the AI provider."""

    gateway_url: str = ""
    api_token: str = ""
    model: str = "claude-opus-4-6"
    api_format: str = "openai"  # "openai" or "anthropic"
    timeout: int = 30
    max_retries: int = 3
